#!/bin/bash
update(){
	local file=/etc/apt/sources.list.d/nala-sources.list
	if [ ! -e $file ]; then sudo touch -d"@0" $file; fi;
	if [ $(date -r $file +%Y%U) != $(date +%Y%U) ]; then
		sudo nala clean --fetch --lists;
		sudo nala fetch --ubuntu jammy --auto -y --fetches 4 -c DE -c AT -c CH;
	fi;
	local this=~/.erxrc/update
	if [ $(date -r $this +%Y%j) != $(date +%Y%j) ]; then
		touch $this;
		sudo nala upgrade -y;
	fi;
	echo Done!
}

fupdate(){
	sudo touch -d"@0" /etc/apt/sources.list.d/nala-sources.list;
	sudo touch -d"@0" ~/.erxrc/update;
	update;
}

update;
